# Generated by Django 5.1.5 on 2025-01-17 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Section',
            new_name='Category',
        ),
        migrations.RenameModel(
            old_name='EventTemplate',
            new_name='Template',
        ),
        migrations.RenameModel(
            old_name='SectionTemplate',
            new_name='TemplateCategory',
        ),
        migrations.RenameModel(
            old_name='ItemTemplate',
            new_name='TemplateItem',
        ),
    ]
