# Generated by Django 5.1.5 on 2025-01-17 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_section_item_category_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='templatecategory',
            old_name='event',
            new_name='template',
        ),
    ]
