# Generated by Django 5.1.5 on 2025-01-20 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_event_author_alter_template_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='templateitem',
            name='icon',
        ),
    ]
