# Generated by Django 5.1.5 on 2025-01-20 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_item_icon_remove_templateitem_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='display_closed_items',
            field=models.BooleanField(default=False),
        ),
    ]
